import type { ComparisonPreference } from "../models/ComparisonPreference";

export const defaultComparisonPreferences: readonly ComparisonPreference[] = [
  {
    id: "coffee",
    label: "Cafe",
    category: "food",
    unitPrice: 6,
    unitLabel: "cafes",
  },
  {
    id: "beer_can",
    label: "Cerveja lata",
    category: "leisure",
    unitPrice: 5,
    unitLabel: "cervejas lata",
  },
  {
    id: "bonbon",
    label: "Bombons",
    category: "food",
    unitPrice: 2.5,
    unitLabel: "bombons",
  },
  {
    id: "burger",
    label: "Hamburguer",
    category: "food",
    unitPrice: 30,
    unitLabel: "hamburgueres",
  },
  {
    id: "netflix",
    label: "Netflix",
    category: "subscription",
    unitPrice: 39.9,
    unitLabel: "meses de Netflix",
  },
  {
    id: "gasoline",
    label: "Gasolina",
    category: "transport",
    unitPrice: 6,
    unitLabel: "litros de gasolina",
  },
  {
    id: "bus_ticket",
    label: "Onibus",
    category: "transport",
    unitPrice: 5,
    unitLabel: "passagens de onibus",
  },
  {
    id: "movie_ticket",
    label: "Cinema",
    category: "leisure",
    unitPrice: 35,
    unitLabel: "ingressos de cinema",
  },
  {
    id: "acai",
    label: "Acai",
    category: "food",
    unitPrice: 18,
    unitLabel: "acais",
  },
  {
    id: "pizza",
    label: "Pizza",
    category: "food",
    unitPrice: 60,
    unitLabel: "pizzas",
  },
  {
    id: "bread",
    label: "Pao frances",
    category: "food",
    unitPrice: 1.2,
    unitLabel: "paes franceses",
  },
  {
    id: "soda_2l",
    label: "Refrigerante 2L",
    category: "food",
    unitPrice: 10,
    unitLabel: "refrigerantes 2L",
  },
  {
    id: "ride_short",
    label: "Uber curto",
    category: "transport",
    unitPrice: 20,
    unitLabel: "corridas curtas",
  },
];
